:truck: Migrate to Artifact Registry
Migrate to Artifact Registry as Container Registry is being deprecated, refs:
https://cloud.google.com/artifact-registry/docs/transition/transition-from-gcr

Note that we had to give the "Artifact Registry Administrator" role to
the service account, the error was:
```
Error: Error creating Repository: googleapi: Error 403:
Permission 'artifactregistry.repositories.create' denied on resource
'//artifactregistry.googleapis.com/projects/<project>/locations/us-central1'
(or it may not exist).
```